version: '3.8'
services:
  client:
    build: .
    container_name: modal-window-client-frontend
    ports:
      - '2006:3000'
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    network_mode: bridge